//CODE-GEN FILE
//This file defines macros to make use of the MathBran serialization format.
//The list of definitions is generated from a spreadsheet in the MathBran project.

#ifndef QMATHBRAN_MACROS
#define QMATHBRAN_MACROS

#define MB_USHORT_CONSTRUCT_SYMBOL 8284 //⁜
#define MB_USHORT_OPEN 9204 //⏴
#define MB_USHORT_CLOSE 9205 //⏵
#define MB_USHORT_ACCENT_ARROW 8594 //→
#define MB_USHORT_ACCENT_BAR 257 //ā
#define MB_USHORT_ACCENT_BREVE 259 //ă
#define MB_USHORT_ACCENT_DOT 551 //ȧ
#define MB_USHORT_ACCENT_DOUBLE_DOTS 228 //ä
#define MB_USHORT_ACCENT_TRIPLE_DOTS 8943 //⋯
#define MB_USHORT_ACCENT_HAT 226 //â
#define MB_USHORT_ACCENT_TILDE 227 //ã
#define MB_USHORT_SUMMATION 8721 //∑
#define MB_USHORT_PRODUCT 8719 //∏
#define MB_USHORT_COPRODUCT 8720 //∐
#define MB_USHORT_INTERSECTION 8898 //⋂
#define MB_USHORT_UNION 8899 //⋃
#define MB_USHORT_UNION_PLUS 10756 //⨄
#define MB_USHORT_BINOMIAL_COEFFICIENTS 98 //b
#define MB_USHORT_CASES 99 //c
#define MB_USHORT_FRACTION 102 //f
#define MB_USHORT_GROUPING_PARENTHESIS 40 //(
#define MB_USHORT_GROUPING_BRACKETS 91 //[
#define MB_USHORT_GROUPING_CEIL 8968 //⌈
#define MB_USHORT_GROUPING_FLOOR 8970 //⌊
#define MB_USHORT_GROUPING_BARS 124 //|
#define MB_USHORT_GROUPING_DOUBLE_BARS 8214 //‖
#define MB_USHORT_INTEGRAL 8747 //∫
#define MB_USHORT_DOUBLE_INTEGRAL 8748 //∬
#define MB_USHORT_TRIPLE_INTEGRAL 8749 //∭
#define MB_USHORT_CONTOUR_INTEGRAL 8750 //∮
#define MB_USHORT_CLOSED_SURFACE_INTEGRAL 8751 //∯
#define MB_USHORT_CLOSED_VOLUME_INTEGRAL 8752 //∰
#define MB_USHORT_MATRIX 8862 //⊞
#define MB_USHORT_ROOT 8730 //√
#define MB_USHORT_SUBSCRIPT 95 //_
#define MB_USHORT_SUPERSCRIPT 94 //^
#define MB_USHORT_DUALSCRIPT 916 //Δ
#define MB_USHORT_EVALSCRIPT 9482 //┊
#define MB_USHORT_LIMIT 108 //l
#define MB_USHORT_UNDERSCRIPTED_MAX 8593 //↑
#define MB_USHORT_UNDERSCRIPTED_MIN 8595 //↓
#define MB_USHORT_UNDERSCRIPTED_SUP 8599 //↗
#define MB_USHORT_UNDERSCRIPTED_INF 8600 //↘

#define MB_CONSTRUCT_SYMBOL QChar(MB_USHORT_CONSTRUCT_SYMBOL) //⁜
#define MB_OPEN QChar(MB_USHORT_OPEN) //⏴
#define MB_CLOSE QChar(MB_USHORT_CLOSE) //⏵
#define MB_ACCENT_ARROW QChar(MB_USHORT_ACCENT_ARROW) //→
#define MB_ACCENT_BAR QChar(MB_USHORT_ACCENT_BAR) //ā
#define MB_ACCENT_BREVE QChar(MB_USHORT_ACCENT_BREVE) //ă
#define MB_ACCENT_DOT QChar(MB_USHORT_ACCENT_DOT) //ȧ
#define MB_ACCENT_DOUBLE_DOTS QChar(MB_USHORT_ACCENT_DOUBLE_DOTS) //ä
#define MB_ACCENT_TRIPLE_DOTS QChar(MB_USHORT_ACCENT_TRIPLE_DOTS) //⋯
#define MB_ACCENT_HAT QChar(MB_USHORT_ACCENT_HAT) //â
#define MB_ACCENT_TILDE QChar(MB_USHORT_ACCENT_TILDE) //ã
#define MB_SUMMATION QChar(MB_USHORT_SUMMATION) //∑
#define MB_PRODUCT QChar(MB_USHORT_PRODUCT) //∏
#define MB_COPRODUCT QChar(MB_USHORT_COPRODUCT) //∐
#define MB_INTERSECTION QChar(MB_USHORT_INTERSECTION) //⋂
#define MB_UNION QChar(MB_USHORT_UNION) //⋃
#define MB_UNION_PLUS QChar(MB_USHORT_UNION_PLUS) //⨄
#define MB_BINOMIAL_COEFFICIENTS QChar(MB_USHORT_BINOMIAL_COEFFICIENTS) //b
#define MB_CASES QChar(MB_USHORT_CASES) //c
#define MB_FRACTION QChar(MB_USHORT_FRACTION) //f
#define MB_GROUPING_PARENTHESIS QChar(MB_USHORT_GROUPING_PARENTHESIS) //(
#define MB_GROUPING_BRACKETS QChar(MB_USHORT_GROUPING_BRACKETS) //[
#define MB_GROUPING_CEIL QChar(MB_USHORT_GROUPING_CEIL) //⌈
#define MB_GROUPING_FLOOR QChar(MB_USHORT_GROUPING_FLOOR) //⌊
#define MB_GROUPING_BARS QChar(MB_USHORT_GROUPING_BARS) //|
#define MB_GROUPING_DOUBLE_BARS QChar(MB_USHORT_GROUPING_DOUBLE_BARS) //‖
#define MB_INTEGRAL QChar(MB_USHORT_INTEGRAL) //∫
#define MB_DOUBLE_INTEGRAL QChar(MB_USHORT_DOUBLE_INTEGRAL) //∬
#define MB_TRIPLE_INTEGRAL QChar(MB_USHORT_TRIPLE_INTEGRAL) //∭
#define MB_CONTOUR_INTEGRAL QChar(MB_USHORT_CONTOUR_INTEGRAL) //∮
#define MB_CLOSED_SURFACE_INTEGRAL QChar(MB_USHORT_CLOSED_SURFACE_INTEGRAL) //∯
#define MB_CLOSED_VOLUME_INTEGRAL QChar(MB_USHORT_CLOSED_VOLUME_INTEGRAL) //∰
#define MB_MATRIX QChar(MB_USHORT_MATRIX) //⊞
#define MB_ROOT QChar(MB_USHORT_ROOT) //√
#define MB_SUBSCRIPT QChar(MB_USHORT_SUBSCRIPT) //_
#define MB_SUPERSCRIPT QChar(MB_USHORT_SUPERSCRIPT) //^
#define MB_DUALSCRIPT QChar(MB_USHORT_DUALSCRIPT) //Δ
#define MB_EVALSCRIPT QChar(MB_USHORT_EVALSCRIPT) //┊
#define MB_LIMIT QChar(MB_USHORT_LIMIT) //l
#define MB_UNDERSCRIPTED_MAX QChar(MB_USHORT_UNDERSCRIPTED_MAX) //↑
#define MB_UNDERSCRIPTED_MIN QChar(MB_USHORT_UNDERSCRIPTED_MIN) //↓
#define MB_UNDERSCRIPTED_SUP QChar(MB_USHORT_UNDERSCRIPTED_SUP) //↗
#define MB_UNDERSCRIPTED_INF QChar(MB_USHORT_UNDERSCRIPTED_INF) //↘

#define MB_ESCAPED_CONSTRUCT_SYMBOL "⁜⁜"
#define MB_ESCAPED_OPEN "⁜⏴"
#define MB_ESCAPED_CLOSE "⁜⏵"

#endif
