//CODE-GEN FILE
//This file is generated from subfolder "meta".
//Changes to this file must be made in the meta project.

#include <QString>
#include <QHash>

//Note: value type is QString because QChar uses UTF-16, but some values are UTF-32 characters
static const QHash<QString, QString> keyword_map = {
    { "|" , "‖" },
    { "adots" , "⋰" },
    { "aleph" , "ℵ" },
    { "alpha" , "α" },
    { "Alpha" , "Α" },
    { "angle" , "∠" },
    { "approx" , "≈" },
    { "ast" , "∗" },
    { "bagmember" , "⋿" },
    { "because" , "∵" },
    { "beta" , "β" },
    { "Beta" , "Β" },
    { "beth" , "ℶ" },
    { "QED" , "■" },
    { "blacktriangleright" , "‣" },
    { "bot" , "⊥" },
    { "bowtie" , "⋈" },
    { "box" , "□" },
    { "bumpeq" , "≏" },
    { "cap" , "∩" },
    { "cdot" , "⋅" },
    { "cdots" , "⋯" },
    { "cent" , "¢" },
    { "checkmark" , "✓" },
    { "chi" , "χ" },
    { "Chi" , "Χ" },
    { "circ" , "∘" },
    { "Colon" , "∷" },
    { "complement" , "∁" },
    { "cong" , "≅" },
    { "copyright" , "©" },
    { "cup" , "∪" },
    { "cupdot" , "⊍" },
    { "dagger" , "†" },
    { "daleth" , "ℸ " },
    { "ddagger" , "‡" },
    { "ddots" , "⋱" },
    { "delta" , "δ" },
    { "Delta" , "Δ" },
    { "diameter" , "⌀" },
    { "dicei" , "⚀" },
    { "diceii" , "⚁" },
    { "diceiii" , "⚂" },
    { "diceiv" , "⚃" },
    { "dicev" , "⚄" },
    { "dicevi" , "⚅" },
    { "digamma" , "ϝ" },
    { "Digamma" , "Ϝ" },
    { "div" , "÷" },
    { "doteq" , "≐" },
    { "dottedsquare" , "⬚" },
    { "downarrow" , "↓" },
    { "emptyset" , "∅" },
    { "epsilon" , "ϵ" },
    { "Epsilon" , "Ε" },
    { "eightnote" , "♪" },
    { "eqcolon" , "∹" },
    { "eqdef" , "≝" },
    { "equiv" , "≡" },
    { "Equiv" , "≣" },
    { "errbar" , "⧮" },
    { "eta" , "η" },
    { "Eta" , "Η" },
    { "Euler" , "ℇ" },
    { "euro" , "€" },
    { "Exclam" , "‼" },
    { "exists" , "∃" },
    { "flat" , "♭" },
    { "forall" , "∀" },
    { "fourth" , "⁗" },
    { "frownie" , "☹" },
    { "gamma" , "γ" },
    { "Gamma" , "Γ" },
    { "geq" , "≥" },
    { "geqq" , "≧" },
    { "gg" , "≫" },
    { "ggg" , "⋙" },
    { "gimel" , "ℷ " },
    { "Im" , "ℑ" },
    { "imath" , "ⅈ" },
    { "implies" , "⇒" },
    { "in" , "∈" },
    { "incr" , "∆" },
    { "infty" , "∞" },
    { "iota" , "ι" },
    { "Iota" , "Ι" },
    { "jmath" , "ⅉ" },
    { "kappa" , "κ" },
    { "Kappa" , "Κ" },
    { "lambda" , "λ" },
    { "Lambda" , "Λ" },
    { "land" , "∧" },
    { "langle" , "⟨" },
    { "lceil" , "⌈" },
    { "leftarrow" , "←" },
    { "Leftarrow" , "⇐" },
    { "leftrightarrow" , "↔" },
    { "Leftrightarrow" , "⇔" },
    { "leq" , "≤" },
    { "leqq" , "≦" },
    { "lfloor" , "⌊" },
    { "ll" , "≪" },
    { "llangle" , "⟪" },
    { "llbracket" , "⟦" },
    { "lll" , "⋘" },
    { "lor" , "∨" },
    { "ltimes" , "⋉" },
    { "maltese" , "✠" },
    { "mapsto" , "↦" },
    { "0" , "𝟘" },
    { "1" , "𝟙" },
    { "2" , "𝟚" },
    { "3" , "𝟛" },
    { "4" , "𝟜" },
    { "5" , "𝟝" },
    { "6" , "𝟞" },
    { "7" , "𝟟" },
    { "8" , "𝟠" },
    { "9" , "𝟡" },
    { "B" , "𝔹" },
    { "C" , "ℂ" },
    { "d" , "ⅆ" },
    { "D" , "𝔻" },
    { "e" , "ℯ" },
    { "E" , "𝔼" },
    { "F" , "𝔽" },
    { "H" , "ℍ" },
    { "J" , "𝕁" },
    { "N" , "ℕ" },
    { "O" , "𝕆" },
    { "P" , "ℙ" },
    { "Q" , "ℚ" },
    { "R" , "ℝ" },
    { "S" , "𝕊" },
    { "T" , "𝕋" },
    { "U" , "𝕌" },
    { "Z" , "ℤ" },
    { "mathfrak{c}" , "𝔠" },
    { "ham" , "ℋ" },
    { "lag" , "ℒ" },
    { "mathsterling" , "£" },
    { "mathyen" , "¥" },
    { "measuredangle" , "∡" },
    { "mho" , "℧" },
    { "mp" , "∓" },
    { "mu" , "μ" },
    { "Mu" , "Μ" },
    { "nabla" , "∇" },
    { "napprox" , "≉" },
    { "natural" , "♮" },
    { "ncong" , "≇ " },
    { "ne" , "≠" },
    { "neg" , "¬" },
    { "neq" , "≠" },
    { "nequiv" , "≢" },
    { "nexists" , "∄" },
    { "ngtr" , "≯" },
    { "ni" , "∋" },
    { "nless" , "≮" },
    { "nmid" , "∤" },
    { "nni" , "∌" },
    { "nsubset" , "⊄" },
    { "nsubseteq" , "⊈" },
    { "nsupset" , "⊅" },
    { "nsupseteq" , "⊉" },
    { "notin" , "∉" },
    { "nu" , "ν" },
    { "Nu" , "Ν" },
    { "odot" , "⨀" },
    { "omega" , "ω" },
    { "Omega" , "Ω" },
    { "ominus" , "⊖" },
    { "omicron" , "ο" },
    { "Omicron" , "Ο" },
    { "oplus" , "⊕" },
    { "oslash" , "⊘" },
    { "otimes" , "⊗" },
    { "P" , "¶ " },
    { "partial" , "∂" },
    { "perp" , "⊥" },
    { "phi" , "ϕ" },
    { "Phi" , "Φ" },
    { "pi" , "π" },
    { "Pi" , "Π" },
    { "Planckconst" , "ℎ" },
    { "pm" , "±" },
    { "prec" , "≺" },
    { "prime" , "′" },
    { "propto" , "∝" },
    { "psi" , "ψ" },
    { "Psi" , "Ψ" },
    { "qoppa" , "ϙ" },
    { "Qoppa" , "Ϙ" },
    { "quarternote" , "♩" },
    { "questeq" , "≟" },
    { "rangle" , "⟩" },
    { "rceil" , "⌉" },
    { "Re" , "ℜ" },
    { "rfloor" , "⌋" },
    { "rho" , "ρ" },
    { "Rho" , "Ρ" },
    { "rightangle" , "∟" },
    { "rightarrow" , "→" },
    { "Rightarrow" , "⇒" },
    { "rightleftarrows" , "⇄" },
    { "rrangle" , "⟫" },
    { "rrbracket" , "⟧" },
    { "rtimes" , "⋊" },
    { "second" , "″" },
    { "sharp" , "♯" },
    { "shuffle" , "⧢" },
    { "sigma" , "σ" },
    { "Sigma" , "Σ" },
    { "sinewave" , "∿" },
    { "sphericalangle" , "∢" },
    { "sqcap" , "⊓" },
    { "sqcup" , "⊔ " },
    { "sqsubset" , "⊏ " },
    { "sqsubseteq" , "⊑" },
    { "sqsupset" , "⊐" },
    { "sqsupseteq" , "⊒" },
    { "subset" , "⊂" },
    { "Subset" , "⋐ " },
    { "subsetcirc" , "⟃" },
    { "subseteq" , "⊆" },
    { "succ" , "≻" },
    { "supset" , "⊃" },
    { "supsetcirc" , "⟄" },
    { "supseteq" , "⊇" },
    { "tau" , "τ" },
    { "Tau" , "Τ" },
    { "textregistered" , "®" },
    { "TM" , "™" },
    { "therefore" , "∴" },
    { "thermod" , "⧧" },
    { "theta" , "θ" },
    { "Theta" , "Θ" },
    { "third" , "‴" },
    { "times" , "×" },
    { "to" , "→" },
    { "top" , "⊤" },
    { "triangleleft" , "◅" },
    { "triangleright" , "▻" },
    { "triangleq" , "≜" },
    { "twonotes" , "♫" },
    { "uparrow" , "↑" },
    { "updownarrow" , "↕" },
    { "uplus" , "⊎" },
    { "upsilon" , "υ" },
    { "Upsilon" , "Υ" },
    { "varepsilon" , "ε" },
    { "varkappa" , "ϰ" },
    { "varphi" , "φ" },
    { "varpi" , "ϖ" },
    { "varrho" , "ϱ" },
    { "varsigma" , "ς" },
    { "vartheta" , "ϑ" },
    { "varTheta" , "ϴ" },
    { "ceqdef" , "≔" },
    { "vdash" , "⊢" },
    { "vDash" , "⊧" },
    { "vdots" , "⋮" },
    { "vee" , "∨" },
    { "veebar" , "⊻" },
    { "warning" , "⚠" },
    { "wedge" , "∧" },
    { "wp" , "℘" },
    { "wr" , "≀" },
    { "xi" , "ξ" },
    { "Xi" , "Ξ" },
    { "Zbar" , "Ƶ" },
    { "zeta" , "ζ" },
    { "Zeta" , "Ζ" },
};

static constexpr int max_keyword_length = 18;

