//CODE-GEN FILE
//This file is generated from subfolder "meta".
//Changes to this file must be made in the meta project.

#define YAWYSIWYGEE_KEYWORDS {\
    { "0" , "𝟘" },\
    { "1" , "𝟙" },\
    { "2" , "𝟚" },\
    { "3" , "𝟛" },\
    { "4" , "𝟜" },\
    { "5" , "𝟝" },\
    { "6" , "𝟞" },\
    { "7" , "𝟟" },\
    { "8" , "𝟠" },\
    { "9" , "𝟡" },\
    { "|" , "‖" },\
    { "adots" , "⋰" },\
    { "aleph" , "ℵ" },\
    { "alpha" , "α" },\
    { "Alpha" , "Α" },\
    { "angle" , "∠" },\
    { "approx" , "≈" },\
    { "ast" , "∗" },\
    { "B" , "𝔹" },\
    { "bagmember" , "⋿" },\
    { "because" , "∵" },\
    { "beta" , "β" },\
    { "Beta" , "Β" },\
    { "beth" , "ℶ" },\
    { "bot" , "⊥" },\
    { "bowtie" , "⋈" },\
    { "box" , "□" },\
    { "bumpeq" , "≏" },\
    { "C" , "ℂ" },\
    { "cap" , "∩" },\
    { "cdot" , "⋅" },\
    { "cdots" , "⋯" },\
    { "cent" , "¢" },\
    { "ceqdef" , "≔" },\
    { "checkmark" , "✓" },\
    { "chi" , "χ" },\
    { "Chi" , "Χ" },\
    { "circ" , "∘" },\
    { "Colon" , "∷" },\
    { "complement" , "∁" },\
    { "cong" , "≅" },\
    { "copyright" , "©" },\
    { "cup" , "∪" },\
    { "cupdot" , "⊍" },\
    { "d" , "ⅆ" },\
    { "D" , "𝔻" },\
    { "dagger" , "†" },\
    { "daleth" , "ℸ " },\
    { "ddagger" , "‡" },\
    { "ddots" , "⋱" },\
    { "delta" , "δ" },\
    { "Delta" , "Δ" },\
    { "diameter" , "⌀" },\
    { "dicei" , "⚀" },\
    { "diceii" , "⚁" },\
    { "diceiii" , "⚂" },\
    { "diceiv" , "⚃" },\
    { "dicev" , "⚄" },\
    { "dicevi" , "⚅" },\
    { "digamma" , "ϝ" },\
    { "Digamma" , "Ϝ" },\
    { "div" , "÷" },\
    { "doteq" , "≐" },\
    { "downarrow" , "↓" },\
    { "e" , "ℯ" },\
    { "E" , "𝔼" },\
    { "eightnote" , "♪" },\
    { "emptyset" , "∅" },\
    { "epsilon" , "ϵ" },\
    { "Epsilon" , "Ε" },\
    { "eqcolon" , "∹" },\
    { "eqdef" , "≝" },\
    { "equiv" , "≡" },\
    { "Equiv" , "≣" },\
    { "errbar" , "⧮" },\
    { "eta" , "η" },\
    { "Eta" , "Η" },\
    { "Euler" , "ℇ" },\
    { "euro" , "€" },\
    { "Exclam" , "‼" },\
    { "exists" , "∃" },\
    { "F" , "𝔽" },\
    { "flat" , "♭" },\
    { "forall" , "∀" },\
    { "fourth" , "⁗" },\
    { "frownie" , "☹" },\
    { "gamma" , "γ" },\
    { "Gamma" , "Γ" },\
    { "geq" , "≥" },\
    { "geqq" , "≧" },\
    { "gg" , "≫" },\
    { "ggg" , "⋙" },\
    { "gimel" , "ℷ " },\
    { "H" , "ℍ" },\
    { "ham" , "ℋ" },\
    { "Im" , "ℑ" },\
    { "imath" , "ⅈ" },\
    { "implies" , "⇒" },\
    { "in" , "∈" },\
    { "incr" , "∆" },\
    { "infty" , "∞" },\
    { "iota" , "ι" },\
    { "Iota" , "Ι" },\
    { "J" , "𝕁" },\
    { "jmath" , "ⅉ" },\
    { "kappa" , "κ" },\
    { "Kappa" , "Κ" },\
    { "lag" , "ℒ" },\
    { "lambda" , "λ" },\
    { "Lambda" , "Λ" },\
    { "land" , "∧" },\
    { "langle" , "⟨" },\
    { "lceil" , "⌈" },\
    { "leftarrow" , "←" },\
    { "Leftarrow" , "⇐" },\
    { "Leftrightarrow" , "↔" },\
    { "Leftrightarrow" , "⇔" },\
    { "leq" , "≤" },\
    { "leqq" , "≦" },\
    { "lfloor" , "⌊" },\
    { "ll" , "≪" },\
    { "llangle" , "⟪" },\
    { "llbracket" , "⟦" },\
    { "lll" , "⋘" },\
    { "lor" , "∨" },\
    { "ltimes" , "⋉" },\
    { "maltese" , "✠" },\
    { "mapsto" , "↦" },\
    { "mathsterling" , "£" },\
    { "mathyen" , "¥" },\
    { "measuredangle" , "∡" },\
    { "mho" , "℧" },\
    { "mp" , "∓" },\
    { "mu" , "μ" },\
    { "Mu" , "Μ" },\
    { "N" , "ℕ" },\
    { "nabla" , "∇" },\
    { "napprox" , "≉" },\
    { "natural" , "♮" },\
    { "ncong" , "≇ " },\
    { "ne" , "≠" },\
    { "neg" , "¬" },\
    { "neq" , "≠" },\
    { "nequiv" , "≢" },\
    { "nexists" , "∄" },\
    { "ngtr" , "≯" },\
    { "ni" , "∋" },\
    { "nless" , "≮" },\
    { "nmid" , "∤" },\
    { "nni" , "∌" },\
    { "notin" , "∉" },\
    { "nsubset" , "⊄" },\
    { "nsubseteq" , "⊈" },\
    { "nsupset" , "⊅" },\
    { "nsupseteq" , "⊉" },\
    { "nu" , "ν" },\
    { "Nu" , "Ν" },\
    { "O" , "𝕆" },\
    { "odot" , "⨀" },\
    { "omega" , "ω" },\
    { "Omega" , "Ω" },\
    { "omicron" , "ο" },\
    { "Omicron" , "Ο" },\
    { "ominus" , "⊖" },\
    { "oplus" , "⊕" },\
    { "oslash" , "⊘" },\
    { "otimes" , "⊗" },\
    { "P" , "ℙ" },\
    { "P" , "¶ " },\
    { "partial" , "∂" },\
    { "perp" , "⊥" },\
    { "phi" , "ϕ" },\
    { "Phi" , "Φ" },\
    { "pi" , "π" },\
    { "Pi" , "Π" },\
    { "Planckconst" , "ℎ" },\
    { "pm" , "±" },\
    { "prec" , "≺" },\
    { "prime" , "′" },\
    { "propto" , "∝" },\
    { "psi" , "ψ" },\
    { "Psi" , "Ψ" },\
    { "Q" , "ℚ" },\
    { "QED" , "■" },\
    { "qoppa" , "ϙ" },\
    { "Qoppa" , "Ϙ" },\
    { "quarternote" , "♩" },\
    { "questeq" , "≟" },\
    { "R" , "ℝ" },\
    { "rangle" , "⟩" },\
    { "rceil" , "⌉" },\
    { "Re" , "ℜ" },\
    { "registered" , "®" },\
    { "rfloor" , "⌋" },\
    { "rho" , "ρ" },\
    { "Rho" , "Ρ" },\
    { "rightangle" , "∟" },\
    { "rightarrow" , "→" },\
    { "Rightarrow" , "⇒" },\
    { "rightleftarrows" , "⇄" },\
    { "rrangle" , "⟫" },\
    { "rrbracket" , "⟧" },\
    { "rtimes" , "⋊" },\
    { "S" , "𝕊" },\
    { "second" , "″" },\
    { "sharp" , "♯" },\
    { "shuffle" , "⧢" },\
    { "sigma" , "σ" },\
    { "Sigma" , "Σ" },\
    { "sinewave" , "∿" },\
    { "sphericalangle" , "∢" },\
    { "sqcap" , "⊓" },\
    { "sqcup" , "⊔ " },\
    { "sqsubset" , "⊏ " },\
    { "sqsubseteq" , "⊑" },\
    { "sqsupset" , "⊐" },\
    { "sqsupseteq" , "⊒" },\
    { "subset" , "⊂" },\
    { "Subset" , "⋐ " },\
    { "subsetcirc" , "⟃" },\
    { "subseteq" , "⊆" },\
    { "succ" , "≻" },\
    { "supset" , "⊃" },\
    { "supsetcirc" , "⟄" },\
    { "supseteq" , "⊇" },\
    { "T" , "𝕋" },\
    { "tau" , "τ" },\
    { "Tau" , "Τ" },\
    { "therefore" , "∴" },\
    { "thermod" , "⧧" },\
    { "theta" , "θ" },\
    { "Theta" , "Θ" },\
    { "third" , "‴" },\
    { "times" , "×" },\
    { "to" , "→" },\
    { "top" , "⊤" },\
    { "triangleleft" , "◅" },\
    { "triangleq" , "≜" },\
    { "triangleright" , "▻" },\
    { "twonotes" , "♫" },\
    { "U" , "𝕌" },\
    { "uparrow" , "↑" },\
    { "updownarrow" , "↕" },\
    { "uplus" , "⊎" },\
    { "upsilon" , "υ" },\
    { "Upsilon" , "Υ" },\
    { "varepsilon" , "ε" },\
    { "varkappa" , "ϰ" },\
    { "varphi" , "φ" },\
    { "varpi" , "ϖ" },\
    { "varrho" , "ϱ" },\
    { "varsigma" , "ς" },\
    { "vartheta" , "ϑ" },\
    { "varTheta" , "ϴ" },\
    { "vdash" , "⊢" },\
    { "vDash" , "⊧" },\
    { "vdots" , "⋮" },\
    { "vee" , "∨" },\
    { "veebar" , "⊻" },\
    { "warning" , "⚠" },\
    { "wedge" , "∧" },\
    { "wp" , "℘" },\
    { "wr" , "≀" },\
    { "xi" , "ξ" },\
    { "Xi" , "Ξ" },\
    { "Z" , "ℤ" },\
    { "Zbar" , "Ƶ" },\
    { "zeta" , "ζ" },\
    { "Zeta" , "Ζ" },\
}

#define YAWYSIWYGEE_NUM_KEYWORDS 269
