//CODE-GEN FILE
//This file is generated from subfolder "meta".
//Changes to this file must be made in the meta project.

#include "YAWYSIWYGEE_keywords.h"
#include <QString>

namespace Keywords {

QString lookup(const QString& key){
    if(key.isEmpty() || key.size() > 15) return QString();

    uint32_t hash = key[0].unicode();
    for(uint8_t i = static_cast<uint8_t>(key.size())-1; i > 0; i--)
        hash += (static_cast<uint32_t>(key[i].unicode()) << 3*i);

    switch(hash){
        case 48:           return key=="0"               ?   "𝟘" : QString();
        case 49:           return key=="1"               ?   "𝟙" : QString();
        case 50:           return key=="2"               ?   "𝟚" : QString();
        case 51:           return key=="3"               ?   "𝟛" : QString();
        case 52:           return key=="4"               ?   "𝟜" : QString();
        case 53:           return key=="5"               ?   "𝟝" : QString();
        case 54:           return key=="6"               ?   "𝟞" : QString();
        case 55:           return key=="7"               ?   "𝟟" : QString();
        case 56:           return key=="8"               ?   "𝟠" : QString();
        case 57:           return key=="9"               ?   "𝟡" : QString();
        case 124:          return key=="|"               ?   "‖" : QString();
        case 538433:       return key=="adots"           ?   "⋰" : QString();
        case 490753:       return key=="aleph"           ?   "ℵ" : QString();
        case 458689:       return key=="alpha"           ?   "α" : QString();
        case 458657:       return key=="Alpha"           ?   "Α" : QString();
        case 476561:       return key=="angle"           ?   "∠" : QString();
        case 4453345:      return key=="approx"          ?   "≈" : QString();
        case 8441:         return key=="ast"             ?   "∗" : QString();
        case 66:           return key=="B"               ?   "𝔹" : QString();
        case 2154153770:   return key=="bagmember"       ?   "⋿" : QString();
        case 30781002:     return key=="because"         ?   "∵" : QString();
        case 57994:        return key=="beta"            ?   "β" : QString();
        case 57962:        return key=="Beta"            ?   "Β" : QString();
        case 61578:        return key=="beth"            ?   "ℶ" : QString();
        case 8410:         return key=="bot"             ?   "⊥" : QString();
        case 3807642:      return key=="bowtie"          ?   "⋈" : QString();
        case 8666:         return key=="box"             ?   "□" : QString();
        case 4181834:      return key=="bumpeq"          ?   "≏" : QString();
        case 67:           return key=="C"               ?   "ℂ" : QString();
        case 8043:         return key=="cap"             ?   "∩" : QString();
        case 67395:        return key=="cdot"            ?   "⋅" : QString();
        case 538435:       return key=="cdots"           ?   "⋯" : QString();
        case 67339:        return key=="cent"            ?   "¢" : QString();
        case 3815371:      return key=="ceqdef"          ?   "≔" : QString();
        case 2063733475:   return key=="checkmark"       ?   "✓" : QString();
        case 7651:         return key=="chi"             ?   "χ" : QString();
        case 7619:         return key=="Chi"             ?   "Χ" : QString();
        case 58923:        return key=="circ"            ?   "∘" : QString();
        case 515259:       return key=="Colon"           ?   "∷" : QString();
        case 479084315:    return key=="complement"      ?   "∁" : QString();
        case 60763:        return key=="cong"            ?   "≅" : QString();
        case 2195239387:   return key=="copyright"       ?   "©" : QString();
        case 8203:         return key=="cup"             ?   "∪" : QString();
        case 4315147:      return key=="cupdot"          ?   "⊍" : QString();
        case 100:          return key=="d"               ?   "ⅆ" : QString();
        case 68:           return key=="D"               ?   "𝔻" : QString();
        case 4209452:      return key=="dagger"          ?   "†" : QString();
        case 3942508:      return key=="daleth"          ?   "ℸ " : QString();
        case 33675716:     return key=="ddagger"         ?   "‡" : QString();
        case 538436:       return key=="ddots"           ?   "⋱" : QString();
        case 464524:       return key=="delta"           ?   "δ" : QString();
        case 464492:       return key=="Delta"           ?   "Δ" : QString();
        case 269829612:    return key=="diameter"        ?   "⌀" : QString();
        case 29503340:     return key=="digamma"         ?   "ϝ" : QString();
        case 29503308:     return key=="Digamma"         ?   "Ϝ" : QString();
        case 8492:         return key=="div"             ?   "÷" : QString();
        case 522972:       return key=="doteq"           ?   "≐" : QString();
        case 2263354780:   return key=="downarrow"       ?   "↓" : QString();
        case 101:          return key=="e"               ?   "ℯ" : QString();
        case 69:           return key=="E"               ?   "𝔼" : QString();
        case 1971006829:   return key=="eightnote"       ?   "♪" : QString();
        case 274077645:    return key=="emptyset"        ?   "∅" : QString();
        case 32977573:     return key=="epsilon"         ?   "ϵ" : QString();
        case 32977541:     return key=="Epsilon"         ?   "Ε" : QString();
        case 32979629:     return key=="eqcolon"         ?   "∹" : QString();
        case 476909:       return key=="eqdef"           ?   "≝" : QString();
        case 545581:       return key=="equiv"           ?   "≡" : QString();
        case 545549:       return key=="Equiv"           ?   "≣" : QString();
        case 4191349:      return key=="errbar"          ?   "⧮" : QString();
        case 7237:         return key=="eta"             ?   "η" : QString();
        case 7205:         return key=="Eta"             ?   "Η" : QString();
        case 526573:       return key=="Euler"           ?   "ℇ" : QString();
        case 65165:        return key=="euro"            ?   "€" : QString();
        case 4031685:      return key=="Exclam"          ?   "‼" : QString();
        case 4310117:      return key=="exists"          ?   "∃" : QString();
        case 70:           return key=="F"               ?   "𝔽" : QString();
        case 66566:        return key=="flat"            ?   "♭" : QString();
        case 4039262:      return key=="forall"          ?   "∀" : QString();
        case 3949854:      return key=="fourth"          ?   "⁗" : QString();
        case 30436790:     return key=="frownie"         ?   "☹" : QString();
        case 460975:       return key=="gamma"           ?   "γ" : QString();
        case 460943:       return key=="Gamma"           ?   "Γ" : QString();
        case 8143:         return key=="geq"             ?   "≥" : QString();
        case 65999:        return key=="geqq"            ?   "≧" : QString();
        case 927:          return key=="gg"              ?   "≫" : QString();
        case 7519:         return key=="ggg"             ?   "⋙" : QString();
        case 501999:       return key=="gimel"           ?   "ℷ" : QString();
        case 72:           return key=="H"               ?   "ℍ" : QString();
        case 7856:         return key=="ham"             ?   "ℋ" : QString();
        case 945:          return key=="Im"              ?   "ℑ" : QString();
        case 492561:       return key=="imath"           ?   "ⅈ" : QString();
        case 33949649:     return key=="implies"         ?   "⇒" : QString();
        case 985:          return key=="in"              ?   "∈" : QString();
        case 65689:        return key=="incr"            ?   "∆" : QString();
        case 562521:       return key=="infty"           ?   "∞" : QString();
        case 58081:        return key=="iota"            ?   "ι" : QString();
        case 58049:        return key=="Iota"            ?   "Ι" : QString();
        case 74:           return key=="J"               ?   "𝕁" : QString();
        case 492562:       return key=="jmath"           ?   "ⅉ" : QString();
        case 462707:       return key=="kappa"           ?   "κ" : QString();
        case 462675:       return key=="Kappa"           ?   "Κ" : QString();
        case 7476:         return key=="lag"             ?   "ℒ" : QString();
        case 3646132:      return key=="lambda"          ?   "λ" : QString();
        case 3646100:      return key=="Lambda"          ?   "Λ" : QString();
        case 59124:        return key=="land"            ?   "∧" : QString();
        case 3812596:      return key=="langle"          ?   "⟨" : QString();
        case 503492:       return key=="lceil"           ?   "⌈" : QString();
        case 2263356692:   return key=="leftarrow"       ?   "←" : QString();
        case 2263356660:   return key=="Leftarrow"       ?   "⇐" : QString();
        case 181970196:    return key=="leftrightarrow"  ?   "↔" : QString();
        case 181970164:    return key=="Leftrightarrow"  ?   "⇔" : QString();
        case 8148:         return key=="leq"             ?   "≤" : QString();
        case 66004:        return key=="leqq"            ?   "≦" : QString();
        case 4254876:      return key=="lfloor"          ?   "⌊" : QString();
        case 972:          return key=="ll"              ?   "≪" : QString();
        case 30500876:     return key=="llangle"         ?   "⟪" : QString();
        case 2189725772:   return key=="llbracket"       ?   "⟦" : QString();
        case 7884:         return key=="lll"             ?   "⋘" : QString();
        case 8292:         return key=="lor"             ?   "∨" : QString();
        case 4245580:      return key=="ltimes"          ?   "⋉" : QString();
        case 30725749:     return key=="maltese"         ?   "✠" : QString();
        case 4179317:      return key=="mapsto"          ?   "↦" : QString();
        case 1142300789:   return key=="mathsterling"    ?   "£" : QString();
        case 32702581:     return key=="mathyen"         ?   "¥" : QString();
        case 2673168853:   return key=="measuredangle"   ?   "∡" : QString();
        case 8045:         return key=="mho"             ?   "℧" : QString();
        case 1005:         return key=="mp"              ?   "∓" : QString();
        case 1045:         return key=="mu"              ?   "μ" : QString();
        case 1013:         return key=="Mu"              ?   "Μ" : QString();
        case 78:           return key=="N"               ?   "ℕ" : QString();
        case 459766:       return key=="nabla"           ?   "∇" : QString();
        case 35626870:     return key=="napprox"         ?   "≉" : QString();
        case 32025206:     return key=="natural"         ?   "♮" : QString();
        case 486214:       return key=="ncong"           ?   "≇" : QString();
        case 918:          return key=="ne"              ?   "≠" : QString();
        case 7510:         return key=="neg"             ?   "¬" : QString();
        case 8150:         return key=="neq"             ?   "≠" : QString();
        case 4364758:      return key=="nequiv"          ?   "≢" : QString();
        case 34481046:     return key=="nexists"         ?   "∄" : QString();
        case 66726:        return key=="ngtr"            ?   "≯" : QString();
        case 950:          return key=="ni"              ?   "∋" : QString();
        case 537358:       return key=="nless"           ?   "≮" : QString();
        case 58902:        return key=="nmid"            ?   "∤" : QString();
        case 7710:         return key=="nni"             ?   "∌" : QString();
        case 512742:       return key=="notin"           ?   "∉" : QString();
        case 34248006:     return key=="nsubset"         ?   "⊄" : QString();
        case 2141885766:   return key=="nsubseteq"       ?   "⊈" : QString();
        case 34255174:     return key=="nsupset"         ?   "⊅" : QString();
        case 2141892934:   return key=="nsupseteq"       ?   "⊉" : QString();
        case 1046:         return key=="nu"              ?   "ν" : QString();
        case 1014:         return key=="Nu"              ?   "Ν" : QString();
        case 79:           return key=="O"               ?   "𝕆" : QString();
        case 67407:        return key=="odot"            ?   "⨀" : QString();
        case 457495:       return key=="omega"           ?   "ω" : QString();
        case 457463:       return key=="Omega"           ?   "Ω" : QString();
        case 32998423:     return key=="omicron"         ?   "ο" : QString();
        case 32998391:     return key=="Omicron"         ?   "Ο" : QString();
        case 4311575:      return key=="ominus"          ?   "⊖" : QString();
        case 538863:       return key=="oplus"           ?   "⊕" : QString();
        case 3936519:      return key=="oslash"          ?   "⊘" : QString();
        case 4245583:      return key=="otimes"          ?   "⊗" : QString();
        case 80:           return key=="P"               ?   "ℙ" : QString();
        case 31987704:     return key=="partial"         ?   "∂" : QString();
        case 65560:        return key=="perp"            ?   "⊥" : QString();
        case 7664:         return key=="phi"             ?   "ϕ" : QString();
        case 7632:         return key=="Phi"             ?   "Φ" : QString();
        case 952:          return key=="pi"              ?   "π" : QString();
        case 920:          return key=="Pi"              ?   "Π" : QString();
        case 363374576:    return key=="Planckconst"     ?   "ℎ" : QString();
        case 984:          return key=="pm"              ?   "±" : QString();
        case 58176:        return key=="prec"            ?   "≺" : QString();
        case 477248:       return key=="prime"           ?   "′" : QString();
        case 4177856:      return key=="propto"          ?   "∝" : QString();
        case 7752:         return key=="psi"             ?   "ψ" : QString();
        case 7720:         return key=="Psi"             ?   "Ψ" : QString();
        case 81:           return key=="Q"               ?   "ℚ" : QString();
        case 4985:         return key=="QED"             ?   "■" : QString();
        case 462825:       return key=="qoppa"           ?   "ϙ" : QString();
        case 462793:       return key=="Qoppa"           ?   "Ϙ" : QString();
        case 1589821529:   return key=="quarternote"     ?   "♩" : QString();
        case 33473369:     return key=="questeq"         ?   "≟" : QString();
        case 82:           return key=="R"               ?   "ℝ" : QString();
        case 3812602:      return key=="rangle"          ?   "⟩" : QString();
        case 503498:       return key=="rceil"           ?   "⌉" : QString();
        case 890:          return key=="Re"              ?   "ℜ" : QString();
        case 2501255002:   return key=="registered"      ?   "®" : QString();
        case 4254882:      return key=="rfloor"          ?   "⌋" : QString();
        case 8050:         return key=="rho"             ?   "ρ" : QString();
        case 8018:         return key=="Rho"             ?   "Ρ" : QString();
        case 2731584890:   return key=="rightangle"      ?   "∟" : QString();
        case 926985594:    return key=="rightarrow"      ?   "→" : QString();
        case 926985562:    return key=="Rightarrow"      ?   "⇒" : QString();
        case 177352058:    return key=="rightleftarrows" ?   "⇄" : QString();
        case 30500930:     return key=="rrangle"         ?   "⟫" : QString();
        case 2189725826:   return key=="rrbracket"       ?   "⟧" : QString();
        case 4245586:      return key=="rtimes"          ?   "⋊" : QString();
        case 83:           return key=="S"               ?   "𝕊" : QString();
        case 3791451:      return key=="second"          ?   "″" : QString();
        case 524275:       return key=="sharp"           ?   "♯" : QString();
        case 30493939:     return key=="shuffle"         ?   "⧢" : QString();
        case 460667:       return key=="sigma"           ?   "σ" : QString();
        case 460635:       return key=="Sigma"           ?   "Σ" : QString();
        case 246470971:    return key=="sinewave"        ?   "∿" : QString();
        case 32016371:     return key=="sphericalangle"  ?   "∢" : QString();
        case 515771:       return key=="sqcap"           ?   "⊓" : QString();
        case 526011:       return key=="sqcup"           ?   "⊔" : QString();
        case 273984187:    return key=="sqsubset"        ?   "⊏" : QString();
        case 4250184379:   return key=="sqsubseteq"      ?   "⊑" : QString();
        case 274041531:    return key=="sqsupset"        ?   "⊐" : QString();
        case 4250241723:   return key=="sqsupseteq"      ?   "⊒" : QString();
        case 4280987:      return key=="subset"          ?   "⊂" : QString();
        case 4280955:      return key=="Subset"          ?   "⋐" : QString();
        case 2565690011:   return key=="subsetcirc"      ?   "⟃" : QString();
        case 267735707:    return key=="subseteq"        ?   "⊆" : QString();
        case 58075:        return key=="succ"            ?   "≻" : QString();
        case 4281883:      return key=="supset"          ?   "⊃" : QString();
        case 2565690907:   return key=="supsetcirc"      ?   "⟄" : QString();
        case 267736603:    return key=="supseteq"        ?   "⊇" : QString();
        case 84:           return key=="T"               ?   "𝕋" : QString();
        case 8380:         return key=="tau"             ?   "τ" : QString();
        case 8348:         return key=="Tau"             ?   "Τ" : QString();
        case 1966493940:   return key=="therefore"       ?   "∴" : QString();
        case 30363892:     return key=="thermod"         ?   "⧧" : QString();
        case 464116:       return key=="theta"           ?   "θ" : QString();
        case 464084:       return key=="Theta"           ?   "Θ" : QString();
        case 475636:       return key=="third"           ?   "‴" : QString();
        case 530684:       return key=="times"           ?   "×" : QString();
        case 1004:         return key=="to"              ?   "→" : QString();
        case 8172:         return key=="top"             ?   "⊤" : QString();
        case 579551300:    return key=="triangleleft"    ?   "◅" : QString();
        case 2139832388:   return key=="triangleq"       ?   "≜" : QString();
        case 2290827332:   return key=="triangleright"   ?   "▻" : QString();
        case 271969260:    return key=="twonotes"        ?   "♫" : QString();
        case 85:           return key=="U"               ?   "𝕌" : QString();
        case 35364917:     return key=="uparrow"         ?   "↑" : QString();
        case 3120786165:   return key=="updownarrow"     ?   "↕" : QString();
        case 538869:       return key=="uplus"           ?   "⊎" : QString();
        case 32977589:     return key=="upsilon"         ?   "υ" : QString();
        case 32977557:     return key=="Upsilon"         ?   "Υ" : QString();
        case 3999623678:   return key=="varepsilon"      ?   "ε" : QString();
        case 236914174:    return key=="varkappa"        ?   "ϰ" : QString();
        case 3932158:      return key=="varphi"          ?   "φ" : QString();
        case 495614:       return key=="varpi"           ?   "ϖ" : QString();
        case 4129790:      return key=="varrho"          ?   "ϱ" : QString();
        case 235869694:    return key=="varsigma"        ?   "ς" : QString();
        case 237635582:    return key=="vartheta"        ?   "ϑ" : QString();
        case 237619198:    return key=="varTheta"        ?   "ϴ" : QString();
        case 491990:       return key=="vdash"           ?   "⊢" : QString();
        case 491734:       return key=="vDash"           ?   "⊧" : QString();
        case 538454:       return key=="vdots"           ?   "⋮" : QString();
        case 7390:         return key=="vee"             ?   "∨" : QString();
        case 4190430:      return key=="veebar"          ?   "⊻" : QString();
        case 31099903:     return key=="warning"         ?   "⚠" : QString();
        case 473759:       return key=="wedge"           ?   "∧" : QString();
        case 1015:         return key=="wp"              ?   "℘" : QString();
        case 1031:         return key=="wr"              ?   "≀" : QString();
        case 960:          return key=="xi"              ?   "ξ" : QString();
        case 928:          return key=="Xi"              ?   "Ξ" : QString();
        case 90:           return key=="Z"               ?   "ℤ" : QString();
        case 65450:        return key=="Zbar"            ?   "Ƶ" : QString();
        case 58018:        return key=="zeta"            ?   "ζ" : QString();
        case 57986:        return key=="Zeta"            ?   "Ζ" : QString();
        default: return QString();
    }
}

};
